2019-03-17 22:58:08,647 - logging_test.py[line: 32] - DEBUG - debug message: 0
2019-03-17 22:58:08,651 - logging_test.py[line: 33] - INFO - info message: 0
2019-03-17 22:58:08,651 - logging_test.py[line: 34] - WARNING - warning message: 0
2019-03-17 22:58:08,652 - logging_test.py[line: 35] - ERROR - error message: 0
2019-03-17 22:58:08,653 - logging_test.py[line: 36] - CRITICAL - critical message: 0
2019-03-17 22:58:09,653 - logging_test.py[line: 32] - DEBUG - debug message: 1
2019-03-17 22:58:09,658 - logging_test.py[line: 33] - INFO - info message: 1
2019-03-17 22:58:09,658 - logging_test.py[line: 34] - WARNING - warning message: 1
2019-03-17 22:58:09,659 - logging_test.py[line: 35] - ERROR - error message: 1
2019-03-17 22:58:09,659 - logging_test.py[line: 36] - CRITICAL - critical message: 1
2019-03-17 22:58:10,659 - logging_test.py[line: 32] - DEBUG - debug message: 2
2019-03-17 22:58:10,659 - logging_test.py[line: 33] - INFO - info message: 2
2019-03-17 22:58:10,659 - logging_test.py[line: 34] - WARNING - warning message: 2
2019-03-17 22:58:10,660 - logging_test.py[line: 35] - ERROR - error message: 2
2019-03-17 22:58:10,660 - logging_test.py[line: 36] - CRITICAL - critical message: 2
2019-03-17 22:58:11,661 - logging_test.py[line: 32] - DEBUG - debug message: 3
2019-03-17 22:58:11,661 - logging_test.py[line: 33] - INFO - info message: 3
2019-03-17 22:58:11,661 - logging_test.py[line: 34] - WARNING - warning message: 3
2019-03-17 22:58:11,661 - logging_test.py[line: 35] - ERROR - error message: 3
2019-03-17 22:58:11,661 - logging_test.py[line: 36] - CRITICAL - critical message: 3
2019-03-17 22:58:12,663 - logging_test.py[line: 32] - DEBUG - debug message: 4
2019-03-17 22:58:12,663 - logging_test.py[line: 33] - INFO - info message: 4
2019-03-17 22:58:12,663 - logging_test.py[line: 34] - WARNING - warning message: 4
2019-03-17 22:58:12,663 - logging_test.py[line: 35] - ERROR - error message: 4
2019-03-17 22:58:12,663 - logging_test.py[line: 36] - CRITICAL - critical message: 4
2019-03-17 22:58:13,664 - logging_test.py[line: 32] - DEBUG - debug message: 5
2019-03-17 22:58:13,664 - logging_test.py[line: 33] - INFO - info message: 5
2019-03-17 22:58:13,664 - logging_test.py[line: 34] - WARNING - warning message: 5
2019-03-17 22:58:13,664 - logging_test.py[line: 35] - ERROR - error message: 5
2019-03-17 22:58:13,665 - logging_test.py[line: 36] - CRITICAL - critical message: 5
2019-03-17 22:58:14,666 - logging_test.py[line: 32] - DEBUG - debug message: 6
2019-03-17 22:58:14,666 - logging_test.py[line: 33] - INFO - info message: 6
2019-03-17 22:58:14,666 - logging_test.py[line: 34] - WARNING - warning message: 6
2019-03-17 22:58:14,666 - logging_test.py[line: 35] - ERROR - error message: 6
2019-03-17 22:58:14,666 - logging_test.py[line: 36] - CRITICAL - critical message: 6
2019-03-17 22:58:15,667 - logging_test.py[line: 32] - DEBUG - debug message: 7
2019-03-17 22:58:15,667 - logging_test.py[line: 33] - INFO - info message: 7
2019-03-17 22:58:15,667 - logging_test.py[line: 34] - WARNING - warning message: 7
2019-03-17 22:58:15,668 - logging_test.py[line: 35] - ERROR - error message: 7
2019-03-17 22:58:15,668 - logging_test.py[line: 36] - CRITICAL - critical message: 7
2019-03-17 22:58:16,668 - logging_test.py[line: 32] - DEBUG - debug message: 8
2019-03-17 22:58:16,668 - logging_test.py[line: 33] - INFO - info message: 8
2019-03-17 22:58:16,668 - logging_test.py[line: 34] - WARNING - warning message: 8
2019-03-17 22:58:16,668 - logging_test.py[line: 35] - ERROR - error message: 8
2019-03-17 22:58:16,669 - logging_test.py[line: 36] - CRITICAL - critical message: 8
2019-03-17 22:58:17,670 - logging_test.py[line: 32] - DEBUG - debug message: 9
2019-03-17 22:58:17,670 - logging_test.py[line: 33] - INFO - info message: 9
2019-03-17 22:58:17,670 - logging_test.py[line: 34] - WARNING - warning message: 9
2019-03-17 22:58:17,670 - logging_test.py[line: 35] - ERROR - error message: 9
2019-03-17 22:58:17,670 - logging_test.py[line: 36] - CRITICAL - critical message: 9
2019-03-17 22:58:37,274 - logging_test.py[line: 32] - DEBUG - debug message: 0
2019-03-17 22:58:37,274 - logging_test.py[line: 33] - INFO - info message: 0
2019-03-17 22:58:37,274 - logging_test.py[line: 34] - WARNING - warning message: 0
2019-03-17 22:58:37,275 - logging_test.py[line: 35] - ERROR - error message: 0
2019-03-17 22:58:37,275 - logging_test.py[line: 36] - CRITICAL - critical message: 0
2019-03-17 22:58:38,275 - logging_test.py[line: 32] - DEBUG - debug message: 1
2019-03-17 22:58:38,275 - logging_test.py[line: 33] - INFO - info message: 1
2019-03-17 22:58:38,275 - logging_test.py[line: 34] - WARNING - warning message: 1
2019-03-17 22:58:38,275 - logging_test.py[line: 35] - ERROR - error message: 1
2019-03-17 22:58:38,275 - logging_test.py[line: 36] - CRITICAL - critical message: 1
2019-03-17 22:58:39,277 - logging_test.py[line: 32] - DEBUG - debug message: 2
2019-03-17 22:58:39,277 - logging_test.py[line: 33] - INFO - info message: 2
2019-03-17 22:58:39,278 - logging_test.py[line: 34] - WARNING - warning message: 2
2019-03-17 22:58:39,278 - logging_test.py[line: 35] - ERROR - error message: 2
2019-03-17 22:58:39,278 - logging_test.py[line: 36] - CRITICAL - critical message: 2
2019-03-17 22:58:40,278 - logging_test.py[line: 32] - DEBUG - debug message: 3
2019-03-17 22:58:40,278 - logging_test.py[line: 33] - INFO - info message: 3
2019-03-17 22:58:40,278 - logging_test.py[line: 34] - WARNING - warning message: 3
2019-03-17 22:58:40,278 - logging_test.py[line: 35] - ERROR - error message: 3
2019-03-17 22:58:40,278 - logging_test.py[line: 36] - CRITICAL - critical message: 3
2019-03-17 22:58:41,280 - logging_test.py[line: 32] - DEBUG - debug message: 4
2019-03-17 22:58:41,280 - logging_test.py[line: 33] - INFO - info message: 4
2019-03-17 22:58:41,280 - logging_test.py[line: 34] - WARNING - warning message: 4
2019-03-17 22:58:41,281 - logging_test.py[line: 35] - ERROR - error message: 4
2019-03-17 22:58:41,281 - logging_test.py[line: 36] - CRITICAL - critical message: 4
2019-03-17 22:58:42,282 - logging_test.py[line: 32] - DEBUG - debug message: 5
2019-03-17 22:58:42,282 - logging_test.py[line: 33] - INFO - info message: 5
2019-03-17 22:58:42,282 - logging_test.py[line: 34] - WARNING - warning message: 5
2019-03-17 22:58:42,282 - logging_test.py[line: 35] - ERROR - error message: 5
2019-03-17 22:58:42,282 - logging_test.py[line: 36] - CRITICAL - critical message: 5
2019-03-17 22:58:43,282 - logging_test.py[line: 32] - DEBUG - debug message: 6
2019-03-17 22:58:43,282 - logging_test.py[line: 33] - INFO - info message: 6
2019-03-17 22:58:43,282 - logging_test.py[line: 34] - WARNING - warning message: 6
2019-03-17 22:58:43,282 - logging_test.py[line: 35] - ERROR - error message: 6
2019-03-17 22:58:43,282 - logging_test.py[line: 36] - CRITICAL - critical message: 6
2019-03-17 22:58:44,282 - logging_test.py[line: 32] - DEBUG - debug message: 7
2019-03-17 22:58:44,282 - logging_test.py[line: 33] - INFO - info message: 7
2019-03-17 22:58:44,282 - logging_test.py[line: 34] - WARNING - warning message: 7
2019-03-17 22:58:44,282 - logging_test.py[line: 35] - ERROR - error message: 7
2019-03-17 22:58:44,282 - logging_test.py[line: 36] - CRITICAL - critical message: 7
2019-03-17 22:58:45,283 - logging_test.py[line: 32] - DEBUG - debug message: 8
2019-03-17 22:58:45,283 - logging_test.py[line: 33] - INFO - info message: 8
2019-03-17 22:58:45,283 - logging_test.py[line: 34] - WARNING - warning message: 8
2019-03-17 22:58:45,283 - logging_test.py[line: 35] - ERROR - error message: 8
2019-03-17 22:58:45,283 - logging_test.py[line: 36] - CRITICAL - critical message: 8
2019-03-17 22:58:46,283 - logging_test.py[line: 32] - DEBUG - debug message: 9
2019-03-17 22:58:46,283 - logging_test.py[line: 33] - INFO - info message: 9
2019-03-17 22:58:46,283 - logging_test.py[line: 34] - WARNING - warning message: 9
2019-03-17 22:58:46,283 - logging_test.py[line: 35] - ERROR - error message: 9
2019-03-17 22:58:46,283 - logging_test.py[line: 36] - CRITICAL - critical message: 9
2019-03-17 23:00:48,100 - logging_test.py[line: 32] - DEBUG - debug message: 0
2019-03-17 23:00:48,100 - logging_test.py[line: 33] - INFO - info message: 0
2019-03-17 23:00:48,100 - logging_test.py[line: 34] - WARNING - warning message: 0
2019-03-17 23:00:48,100 - logging_test.py[line: 35] - ERROR - error message: 0
2019-03-17 23:00:48,100 - logging_test.py[line: 36] - CRITICAL - critical message: 0
2019-03-17 23:00:49,101 - logging_test.py[line: 32] - DEBUG - debug message: 1
2019-03-17 23:00:49,101 - logging_test.py[line: 33] - INFO - info message: 1
2019-03-17 23:00:49,101 - logging_test.py[line: 34] - WARNING - warning message: 1
2019-03-17 23:00:49,101 - logging_test.py[line: 35] - ERROR - error message: 1
2019-03-17 23:00:49,101 - logging_test.py[line: 36] - CRITICAL - critical message: 1
2019-03-17 23:00:50,101 - logging_test.py[line: 32] - DEBUG - debug message: 2
2019-03-17 23:00:50,101 - logging_test.py[line: 33] - INFO - info message: 2
2019-03-17 23:00:50,101 - logging_test.py[line: 34] - WARNING - warning message: 2
2019-03-17 23:00:50,101 - logging_test.py[line: 35] - ERROR - error message: 2
2019-03-17 23:00:50,101 - logging_test.py[line: 36] - CRITICAL - critical message: 2
2019-03-17 23:00:51,102 - logging_test.py[line: 32] - DEBUG - debug message: 3
2019-03-17 23:00:51,102 - logging_test.py[line: 33] - INFO - info message: 3
2019-03-17 23:00:51,102 - logging_test.py[line: 34] - WARNING - warning message: 3
2019-03-17 23:00:51,102 - logging_test.py[line: 35] - ERROR - error message: 3
2019-03-17 23:00:51,102 - logging_test.py[line: 36] - CRITICAL - critical message: 3
2019-03-17 23:00:52,103 - logging_test.py[line: 32] - DEBUG - debug message: 4
2019-03-17 23:00:52,103 - logging_test.py[line: 33] - INFO - info message: 4
2019-03-17 23:00:52,103 - logging_test.py[line: 34] - WARNING - warning message: 4
2019-03-17 23:00:52,103 - logging_test.py[line: 35] - ERROR - error message: 4
2019-03-17 23:00:52,103 - logging_test.py[line: 36] - CRITICAL - critical message: 4
2019-03-17 23:00:53,103 - logging_test.py[line: 32] - DEBUG - debug message: 5
2019-03-17 23:00:53,103 - logging_test.py[line: 33] - INFO - info message: 5
2019-03-17 23:00:53,103 - logging_test.py[line: 34] - WARNING - warning message: 5
2019-03-17 23:00:53,103 - logging_test.py[line: 35] - ERROR - error message: 5
2019-03-17 23:00:53,103 - logging_test.py[line: 36] - CRITICAL - critical message: 5
2019-03-17 23:00:54,103 - logging_test.py[line: 32] - DEBUG - debug message: 6
2019-03-17 23:00:54,103 - logging_test.py[line: 33] - INFO - info message: 6
2019-03-17 23:00:54,103 - logging_test.py[line: 34] - WARNING - warning message: 6
2019-03-17 23:00:54,103 - logging_test.py[line: 35] - ERROR - error message: 6
2019-03-17 23:00:54,103 - logging_test.py[line: 36] - CRITICAL - critical message: 6
2019-03-17 23:00:55,104 - logging_test.py[line: 32] - DEBUG - debug message: 7
2019-03-17 23:00:55,104 - logging_test.py[line: 33] - INFO - info message: 7
2019-03-17 23:00:55,104 - logging_test.py[line: 34] - WARNING - warning message: 7
2019-03-17 23:00:55,104 - logging_test.py[line: 35] - ERROR - error message: 7
2019-03-17 23:00:55,104 - logging_test.py[line: 36] - CRITICAL - critical message: 7
2019-03-17 23:00:56,105 - logging_test.py[line: 32] - DEBUG - debug message: 8
2019-03-17 23:00:56,105 - logging_test.py[line: 33] - INFO - info message: 8
2019-03-17 23:00:56,105 - logging_test.py[line: 34] - WARNING - warning message: 8
2019-03-17 23:00:56,105 - logging_test.py[line: 35] - ERROR - error message: 8
2019-03-17 23:00:56,106 - logging_test.py[line: 36] - CRITICAL - critical message: 8
2019-03-17 23:00:57,106 - logging_test.py[line: 32] - DEBUG - debug message: 9
2019-03-17 23:00:57,107 - logging_test.py[line: 33] - INFO - info message: 9
2019-03-17 23:00:57,107 - logging_test.py[line: 34] - WARNING - warning message: 9
2019-03-17 23:00:57,107 - logging_test.py[line: 35] - ERROR - error message: 9
2019-03-17 23:00:57,107 - logging_test.py[line: 36] - CRITICAL - critical message: 9
